# Generated by Django 4.2.6 on 2024-05-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='to_show',
            new_name='is_private',
        ),
    ]
